// Scans the repo checked out into this job's own workspace for every cicd/Jenkinsfile
// and generates one pipeline job per match, named after the folder that owns it
// (e.g. Backend/gallery/cicd/Jenkinsfile -> job "gallery",
//       Infrastructure/modules/dynamodb/cicd/Jenkinsfile -> job "dynamodb").
// Rerun this job (Build Now) any time a module/Lambda folder is added, moved, or renamed.

def repoUrl = 'https://github.com/HridayBuilds/Glimpses.git'
def credentialsId = 'github-glimpses-pat'
def branch = '*/main'

def jenkinsfiles = []
new File('.').eachFileRecurse { f ->
    if (f.path.endsWith('cicd/Jenkinsfile')) {
        jenkinsfiles << f.path.replaceFirst('^\\./', '')
    }
}

jenkinsfiles.each { path ->
    def jobName = path.split('/')[-3]

    pipelineJob(jobName) {
        description("Auto-generated by glimpses-seed from ${path}")
        definition {
            cpsScmFlowDefinition {
                scm {
                    git {
                        remote {
                            url(repoUrl)
                            credentials(credentialsId)
                        }
                        branch(branch)
                    }
                }
                scriptPath(path)
            }
        }
    }
}
