// Reads the list of cicd/Jenkinsfile paths (one per line, produced by a shell "find"
// build step that must run before this one) and generates one pipeline job per match,
// named after the folder that owns it (e.g. Backend/gallery/cicd/Jenkinsfile -> job
// "gallery", Infrastructure/modules/dynamodb/cicd/Jenkinsfile -> job "dynamodb").
// Rerun this job (Build Now) any time a module/Lambda folder is added, moved, or renamed.
//
// The scan itself is NOT done in this Groovy script — Job DSL scripts run inside
// Jenkins' sandboxed interpreter, where a recursive file-walk closure is extremely
// slow (continuation-passing overhead per file). Real `find` in a preceding shell
// build step does the same scan in milliseconds.
//
// The SCM/definition block is injected as raw XML via configure(), not Job DSL's
// typed cpsScmFlowDefinition/scm/git DSL — that typed DSL's "git" method isn't
// resolvable on this Jenkins/job-dsl-plugin/git-plugin combination (fails with
// "DescribableListContext.git() is applicable" regardless of closure shape tried).
// This XML shape is copied from an existing, already-working job's config.xml on
// this same instance, so it's guaranteed compatible.

def repoUrl = 'https://github.com/HridayBuilds/Glimpses.git'
def credentialsId = 'github-glimpses-pat'
def branch = '*/main'

def jenkinsfiles = readFileFromWorkspace('jenkinsfiles.txt').readLines().findAll { it.trim() }

jenkinsfiles.each { path ->
    def jobName = path.split('/')[-3]

    pipelineJob(jobName) {
        description("Auto-generated by glimpses-seed from ${path}")
        configure { project ->
            def definitionXml = """
<definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition" plugin="workflow-cps">
  <scm class="hudson.plugins.git.GitSCM" plugin="git">
    <configVersion>2</configVersion>
    <userRemoteConfigs>
      <hudson.plugins.git.UserRemoteConfig>
        <url>${repoUrl}</url>
        <credentialsId>${credentialsId}</credentialsId>
      </hudson.plugins.git.UserRemoteConfig>
    </userRemoteConfigs>
    <branches>
      <hudson.plugins.git.BranchSpec>
        <name>${branch}</name>
      </hudson.plugins.git.BranchSpec>
    </branches>
    <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
    <submoduleCfg class="empty-list"/>
    <extensions/>
  </scm>
  <scriptPath>${path}</scriptPath>
  <lightweight>true</lightweight>
</definition>
"""
            def newDefinition = new XmlParser().parseText(definitionXml)
            def existingDefinition = (project / definition)[0]
            existingDefinition.replaceNode(newDefinition)
        }
    }
}
